<?xml version="1.0"?>
<package format="3">

	<name>robot_change_detector</name>

	<version>0.0.1</version>

	<description>
		TurtleBot environment change detection system
	</description>

	<maintainer email="team@example.com">
		robot_team
	</maintainer>

	<license>Apache-2.0</license>

	<buildtool_depend>ament_python</buildtool_depend>

	<depend>rclpy</depend>
	<depend>sensor_msgs</depend>
	<depend>nav_msgs</depend>
	<depend>geometry_msgs</depend>
	<depend>nav2_simple_commander</depend>
	<depend>tf2_ros</depend>
	<depend>cv_bridge</depend>

	<exec_depend>python3-numpy</exec_depend>
	<exec_depend>python3-opencv</exec_depend>
	<exec_depend>ros-jazzy-cv-bridge</exec_depend>

	<export>
		<build_type>ament_python</build_type>
	</export>

</package>